### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by drididh** [DatavenueLiveObjects/Azure-IoT-Hub-connector-to-install-on-Azure#12]
we get an error after 1 day of service and the connector can't create new threads (java.lang.OutOfMemoryError: unable to create new native thread).

A restart of the VM solve this issue but we don't want to check each day if the connector need to be restarted.

I attach the last log file with errors in this post.
[logs17-11.txt](https://github.com/DatavenueLiveObjects/Azure-IoT-Hub-connector-to-install-on-Azure/files/7554169/logs17-11.txt)
E)
Best regards,
D. Dridi (CORIANCE)

**Comment by szlisiecki** [comment]
Hello,
Thanks for reporting a bug. I fixed it. Please try to use the latest version - v1.1

Best regards 
Szymon Lisiecki
